### PR TITLE
Validate email address and redirect back if invalid

### PR DESCRIPTION
**Pull request by cjsewell**

### CODE REVIEW

**Comment by dhensby** [comment]
The framework has it's own validator for emails as a station method on Email. 

We should use that as filter_var doesn't take account of utf8 chars in the address.

**Comment by cjsewell** [comment]
Ahh ok, thanks for that. Fixed it, and also changed the error message to use translations.

**Comment by dhensby** [comment]
You need Email::is_valid_address, sorry

**Comment by cjsewell** [comment]
Doh, no worries. 
Third times a charm. Should be good now

**Comment by dhensby** [comment]
Sorry, you're going to hate me.. I just realised the line just above this change (401) strips all "unexpected" chars (ie: UTF-8 ones)... I'm not sure if that should be removed or not.. seems a strange thing to do.

We shouldn't edit the submitted value and then accept it based on our changes, we should take the user input and tell them if it's valid...

At the moment it looks like the email address: `me+test@example.com` would become `metest@example.com`, be passed as valid and added as a subscriber.. meaning the user would never get the emails!

I know this is strictly scope creep for this PR, but I think that needs to be resolved, really...

**Comment by cjsewell** [comment]
Ha, no worries!

I also noticed a rather redundant `isset($data['Email'])`, so I cleaned that up as well.

Let me know if you want me to start a new PR as the changes are outside of this ones initial purpose.

Cheers

**Comment by dhensby** [comment]
Fantastic, looks great, thanks.

**Pull request merged**
